# Generated by Django 2.0 on 2020-10-20 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SquirrelCensusDatas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
                ('Unique_Squirrel_ID', models.CharField(max_length=20)),
                ('Shift', models.CharField(max_length=5)),
                ('Date', models.CharField(max_length=10)),
                ('Age', models.CharField(max_length=20)),
            ],
        ),
    ]
