# Generated by Django 3.1.2 on 2020-10-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(help_text='Latitude')),
                ('longitude', models.FloatField(help_text='Longitude')),
                ('unique_squirrel_id', models.CharField(help_text='Unique Squirrel ID', max_length=100)),
                ('shift', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], default='AM', help_text='Shift', max_length=2)),
                ('date', models.DateField(help_text='Date')),
                ('age', models.CharField(choices=[('ADULT', 'ADULT'), ('JUVENILE', 'JUVENILE'), ('OTHER', 'OTHER')], default='ADULT', help_text='Age', max_length=10)),
            ],
        ),
    ]
