# Generated by Django 3.1.2 on 2020-10-13 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0002_auto_20201013_0221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='squirrel',
            old_name='approches',
            new_name='approaches',
        ),
    ]
