# Generated by Django 3.1.2 on 2020-10-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0003_auto_20201013_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='age',
            field=models.CharField(choices=[('ADULT', 'ADULT'), ('JUVENILE', 'JUVENILE'), ('OTHER', 'OTHER')], default='None', help_text='Age', max_length=10),
        ),
    ]
