# Generated by Django 3.1.2 on 2020-10-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0004_auto_20201019_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='age',
            field=models.CharField(choices=[('ADULT', 'ADULT'), ('JUVENILE', 'JUVENILE'), ('OTHER', 'OTHER')], default='ADULT', help_text='Age', max_length=10),
        ),
    ]
